logging:
  level: info
mybatis:
  type-aliases-package: com.j.model
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  data:
    mongodb:
      connections-per-host: 22
      min-connections-per-host: 12
      database: test
      port: 17017
      host: 10.25.245.121
  rabbitmq:
      host: 10.25.245.121
      port: 8088
      username: guest
      password: guest
      virtual-host: /wq
      listener:
        simple:
          concurrency: 30
          max-concurrency: 100
          retry:
            initial-interval: 2000
            enabled: true
            max-interval: 50000
            max-attempts: 10
  devtools:
    remote: #远程调试 org.springframework.boot.devtools.RemoteSpringApplication
      secret: wq
 #actuator使用,lei
management:
  security:
    enabled: false

#cron:
#  pattern: 0/15 * * * * ?
